version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "@babel/preset-env"
        versions:
          - 7.12.11
          - 7.12.13
          - 7.12.16
          - 7.12.17
          - 7.13.0
          - 7.13.10
          - 7.13.12
          - 7.13.15
          - 7.13.5
          - 7.13.8
          - 7.13.9
      - dependency-name: y18n
        versions:
          - 4.0.1
          - 4.0.2
      - dependency-name: typescript
        versions:
          - 4.2.2
          - 4.2.3
      - dependency-name: node-notifier
        versions:
          - 8.0.1
      - dependency-name: ini
        versions:
          - 1.3.8
      - dependency-name: "@types/mongodb"
        versions:
          - 3.6.1
