name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This is the stale issue."
          stale-pr-message: "This is the stale pull request."
          stale-issue-label: "no activity"
          stale-pr-label: "no activity"
